---
# tasks file for roles/roles-features
- name: Instalando recursos e ferramentas 
  win_feature:
    state: present
    name: "{{ item }}"
  with_items: 
        - FileAndStorage-Services
        - Storage-Services
        - Web-Server
        - Web-WebServer
        - Web-Common-Http
        - Web-Default-Doc
        - Web-Dir-Browsing
        - Web-Http-Errors
        - Web-Static-Content
        - Web-Health
        - Web-Http-Logging
        - Web-Performance
        - Web-Stat-Compression
        - Web-Security
        - Web-Filtering
        - Web-App-Dev
        - Web-Net-Ext45
        - Web-Asp-Net45
        - Web-ISAPI-Ext
        - Web-ISAPI-Filter
        - Web-Mgmt-Tools
        - Web-Mgmt-Console
        # - NET-Framework-Features
        # - NET-Framework-Core
        # - NET-Framework-45-Features
        # - NET-Framework-45-Core
        # - NET-Framework-45-ASPNET
        # - NET-WCF-Services45
        # - NET-WCF-HTTP-Activation45
        # - NET-WCF-TCP-PortSharing45
        # - FS-SMB1
        - Telnet-Client
        # - User-Interfaces-Infra
        # - Server-Gui-Mgmt-Infra
        # - Server-Gui-Shell
        # - PowerShellRoot
        # - PowerShell
        # - PowerShell-V2
        # - PowerShell-ISE
        # - WAS
        # - WAS-Process-Model
        # - WAS-Config-APIs
        # - WoW64-Support   